package com.hrm.employeemanagement.domain.authorization;

public enum PermissionCode {

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_UPDATE_ROLE,
    USER_TOGGLE_STATUS,
    ORG_UNIT_READ,
    PROJECT_READ,
    PROJECT_CREATE,

    EMPLOYEE_READ,
    EMPLOYEE_UPDATE,
    EMPLOYEE_SKILL_READ,
    EMPLOYEE_SKILL_DECLARE,
    EMPLOYEE_SKILL_APPROVE,

    SKILL_READ,
    SKILL_CREATE,
    SKILL_UPDATE,
    SKILL_MERGE,
    SKILL_DEACTIVATE
}
