package com.hrm.employeemanagement.domain.authorization;

public enum PermissionCode {

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_UPDATE_ROLE,
    USER_TOGGLE_STATUS,
    ORG_UNIT_READ,
    ORG_UNIT_MANAGE,
    PROJECT_READ,
    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_WBS_MANAGE,
    PROJECT_MILESTONE_MANAGE,
    PROJECT_RESOURCE_DEMAND_ESTIMATE,
    PROJECT_RESOURCE_DEMAND_READ,
    EMPLOYEE_READ,
    EMPLOYEE_UPDATE,
    EMPLOYEE_SKILL_READ,
    EMPLOYEE_SKILL_DECLARE,
    EMPLOYEE_SKILL_APPROVE,
    SKILL_READ,
    SKILL_CREATE,
    SKILL_UPDATE,
    SKILL_MERGE,
    SKILL_DEACTIVATE,
    RESOURCE_ALLOCATION_READ,
    RESOURCE_ALLOCATION_MANAGE,
    RESOURCE_SEARCH
}
