package com.hrm.employeemanagement.infrastructure.config;

import com.hrm.employeemanagement.domain.role.RoleCode;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.entity.EmployeeJpaEntity;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.entity.RoleJpaEntity;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.entity.UserJpaEntity;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.repository.SpringDataEmployeeRepository;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.repository.SpringDataRoleRepository;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.repository.SpringDataUserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.UUID;

/**
 * Database Initializer & Secure Admin Provisioner.
 * Seeds static roles and dynamically provisions the initial administrator
 * using environment variables or auto-generated high-entropy secrets.
 */
@Component
public class DataInitializer implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DataInitializer.class);

    private final SpringDataRoleRepository roleRepository;
    private final SpringDataUserRepository userRepository;
    private final SpringDataEmployeeRepository employeeRepository;
    private final PasswordEncoder passwordEncoder;

    @Value("${app.security.initial-admin.enabled:true}")
    private boolean initialAdminEnabled;

    @Value("${app.security.initial-admin.username:admin}")
    private String initialAdminUsername;

    @Value("${app.security.initial-admin.password:}")
    private String initialAdminPassword;

    public DataInitializer(SpringDataRoleRepository roleRepository,
                           SpringDataUserRepository userRepository,
                           SpringDataEmployeeRepository employeeRepository,
                           PasswordEncoder passwordEncoder) {
        this.roleRepository = roleRepository;
        this.userRepository = userRepository;
        this.employeeRepository = employeeRepository;
        this.passwordEncoder = passwordEncoder;
    }

    public void setInitialAdminEnabled(boolean initialAdminEnabled) {
        this.initialAdminEnabled = initialAdminEnabled;
    }

    public void setInitialAdminUsername(String initialAdminUsername) {
        this.initialAdminUsername = initialAdminUsername;
    }

    public void setInitialAdminPassword(String initialAdminPassword) {
        this.initialAdminPassword = initialAdminPassword;
    }

    @Override
    public void run(String... args) throws Exception {
        // 1. Seed system roles (VT-01 -> VT-07)
        for (RoleCode rc : RoleCode.values()) {
            if (roleRepository.findByCode(rc.getCode()).isEmpty()) {
                roleRepository.save(new RoleJpaEntity(null, rc.getCode(), rc.getName()));
            }
        }

        // 2. Provision initial admin if enabled and no active administrator exists
        if (initialAdminEnabled) {
            provisionInitialAdmin();
        }
    }

    private void provisionInitialAdmin() {
        String username = (initialAdminUsername != null && !initialAdminUsername.trim().isEmpty())
                ? initialAdminUsername.trim()
                : "admin";

        if (userRepository.countActiveAdmins() == 0 && userRepository.findByUsername(username).isEmpty()) {
            RoleJpaEntity adminRole = roleRepository.findByCode("VT-06")
                    .orElseThrow(() -> new IllegalStateException("Role VT-06 (Quản trị viên) chưa tồn tại trong cơ sở dữ liệu"));

            String rawPassword;
            boolean isAutoGenerated = false;

            if (initialAdminPassword != null && !initialAdminPassword.trim().isEmpty()) {
                rawPassword = initialAdminPassword.trim();
            } else {
                rawPassword = generateSecureRandomPassword();
                isAutoGenerated = true;
            }

            UserJpaEntity adminUser = new UserJpaEntity(
                    null,
                    username,
                    passwordEncoder.encode(rawPassword),
                    adminRole,
                    true
            );
            UserJpaEntity savedAdmin = userRepository.save(adminUser);

            if (employeeRepository.findByUserId(savedAdmin.getId()).isEmpty()) {
                EmployeeJpaEntity adminEmployee = new EmployeeJpaEntity(
                        null,
                        savedAdmin.getId(),
                        null,
                        "EMP-ADMIN",
                        "Quản trị viên hệ thống",
                        false,
                        40,
                        "ACTIVE"
                );
                employeeRepository.save(adminEmployee);
            }

            if (isAutoGenerated) {
                log.warn("""
                        
                        ========================================================================================
                         SECURITY WARNING: INITIAL ADMIN ACCOUNT HAS BEEN GENERATED WITH A RANDOM PASSWORD!
                         Username: {}
                         Temporary Password: {}
                         PLEASE LOG IN AND CHANGE THIS PASSWORD IMMEDIATELY!
                        ========================================================================================
                        """, username, rawPassword);
            } else {
                log.info("Initial admin account '{}' successfully provisioned from environment configuration.", username);
            }
        }
    }

    private String generateSecureRandomPassword() {
        return UUID.randomUUID().toString().replace("-", "").substring(0, 16);
    }
}
