package com.hrm.employeemanagement.infrastructure.config;

import com.hrm.employeemanagement.domain.role.RoleCode;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.entity.DepartmentJpaEntity;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.entity.EmployeeJpaEntity;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.entity.RoleJpaEntity;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.entity.UserJpaEntity;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.repository.SpringDataDepartmentRepository;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.repository.SpringDataEmployeeRepository;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.repository.SpringDataRoleRepository;
import com.hrm.employeemanagement.infrastructure.adapter.outbound.persistence.user.repository.SpringDataUserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

/**
 * Database Initializer & Secure Admin Provisioner.
 * Guarantees atomic (@Transactional) and resource-level idempotent bootstrap of
 * roles, root department, and the initial administrator account.
 */
@Component
public class DataInitializer implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DataInitializer.class);

    private final SpringDataRoleRepository roleRepository;
    private final SpringDataDepartmentRepository departmentRepository;
    private final SpringDataUserRepository userRepository;
    private final SpringDataEmployeeRepository employeeRepository;
    private final PasswordEncoder passwordEncoder;

    @Value("${app.security.initial-admin.enabled:true}")
    private boolean initialAdminEnabled;

    @Value("${app.security.initial-admin.username:admin}")
    private String initialAdminUsername;

    @Value("${app.security.initial-admin.password:}")
    private String initialAdminPassword;

    public DataInitializer(SpringDataRoleRepository roleRepository,
                           SpringDataDepartmentRepository departmentRepository,
                           SpringDataUserRepository userRepository,
                           SpringDataEmployeeRepository employeeRepository,
                           PasswordEncoder passwordEncoder) {
        this.roleRepository = roleRepository;
        this.departmentRepository = departmentRepository;
        this.userRepository = userRepository;
        this.employeeRepository = employeeRepository;
        this.passwordEncoder = passwordEncoder;
    }

    public void setInitialAdminEnabled(boolean initialAdminEnabled) {
        this.initialAdminEnabled = initialAdminEnabled;
    }

    public void setInitialAdminUsername(String initialAdminUsername) {
        this.initialAdminUsername = initialAdminUsername;
    }

    public void setInitialAdminPassword(String initialAdminPassword) {
        this.initialAdminPassword = initialAdminPassword;
    }

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        // 1. Seed system roles (VT-01 -> VT-07) idempotently
        for (RoleCode rc : RoleCode.values()) {
            if (roleRepository.findByCode(rc.getCode()).isEmpty()) {
                roleRepository.save(new RoleJpaEntity(null, rc.getCode(), rc.getName()));
            }
        }

        // 2. Seed default Root Department (PB-01) idempotently
        DepartmentJpaEntity defaultDept = departmentRepository.findByCode("PB-01")
                .orElseGet(() -> departmentRepository.save(new DepartmentJpaEntity(null, "PB-01", "Ban giám đốc", null)));

        // 3. Provision initial admin user and employee profile atomically & idempotently
        if (initialAdminEnabled) {
            provisionInitialAdmin(defaultDept);
        }
    }

    private void provisionInitialAdmin(DepartmentJpaEntity defaultDept) {
        String username = (initialAdminUsername != null && !initialAdminUsername.trim().isEmpty())
                ? initialAdminUsername.trim()
                : "admin";

        // Find existing admin or create a new one
        UserJpaEntity adminUser = userRepository.findByUsername(username).orElse(null);
        boolean isNewUser = false;
        String rawPassword = null;
        boolean isAutoGenerated = false;

        if (adminUser == null && userRepository.countActiveAdmins() == 0) {
            RoleJpaEntity adminRole = roleRepository.findByCode("VT-06")
                    .orElseThrow(() -> new IllegalStateException("Role VT-06 (Quản trị viên) chưa tồn tại trong cơ sở dữ liệu"));

            if (initialAdminPassword != null && !initialAdminPassword.trim().isEmpty()) {
                rawPassword = initialAdminPassword.trim();
            } else {
                rawPassword = generateSecureRandomPassword();
                isAutoGenerated = true;
            }

            UserJpaEntity newAdmin = new UserJpaEntity(
                    null,
                    username,
                    passwordEncoder.encode(rawPassword),
                    adminRole,
                    true
            );
            adminUser = userRepository.save(newAdmin);
            isNewUser = true;
        }

        // Self-Healing: Ensure the Admin User always has a linked Employee profile
        if (adminUser != null && employeeRepository.findByUserId(adminUser.getId()).isEmpty()) {
            EmployeeJpaEntity adminEmployee = new EmployeeJpaEntity(
                    null,
                    adminUser.getId(),
                    defaultDept.getId(),
                    "EMP-ADMIN",
                    "Quản trị viên hệ thống",
                    false,
                    40,
                    "ACTIVE"
            );
            employeeRepository.save(adminEmployee);
        }

        // Log warnings/info on initial creation
        if (isNewUser) {
            if (isAutoGenerated) {
                log.warn("""
                        
                        ========================================================================================
                         SECURITY WARNING: INITIAL ADMIN ACCOUNT HAS BEEN GENERATED WITH A RANDOM PASSWORD!
                         Username: {}
                         Temporary Password: {}
                         PLEASE LOG IN AND CHANGE THIS PASSWORD IMMEDIATELY!
                        ========================================================================================
                        """, username, rawPassword);
            } else {
                log.info("Initial admin account '{}' successfully provisioned from environment configuration.", username);
            }
        }
    }

    private String generateSecureRandomPassword() {
        return UUID.randomUUID().toString().replace("-", "").substring(0, 16);
    }
}
