package com.hrm.employeemanagement.infrastructure.transaction.scenario;

import java.time.LocalDateTime;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataIntegrityViolationException;

import com.hrm.employeemanagement.application.dto.scenario.CreateScenarioCommand;
import com.hrm.employeemanagement.application.dto.scenario.ScenarioResult;
import com.hrm.employeemanagement.application.port.inbound.scenario.CreateSimulationScenarioUseCase;
import com.hrm.employeemanagement.domain.exception.scenario.DuplicateScenarioCodeException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("RetryableCreateSimulationScenarioUseCaseDecorator Unit Tests")
class RetryableCreateSimulationScenarioUseCaseDecoratorTest {

    @Mock
    private CreateSimulationScenarioUseCase transactionalDelegate;

    private RetryableCreateSimulationScenarioUseCaseDecorator decorator;

    @BeforeEach
    void setUp() {
        decorator = new RetryableCreateSimulationScenarioUseCaseDecorator(transactionalDelegate, 3);
    }

    @Test
    @DisplayName("Client chỉ định mã bị trùng -> Ném DuplicateScenarioCodeException ngay lập tức, không retry")
    void testCreateScenario_ClientProvidedDuplicateCode_ThrowsImmediatelyWithoutRetry() {
        CreateScenarioCommand command = new CreateScenarioCommand(
                "SCN-CUSTOM-001", "Kịch bản test", "Mô tả", 10L, 2026, 38, 8
        );

        when(transactionalDelegate.createScenario(command))
                .thenThrow(new DuplicateScenarioCodeException("SCN-CUSTOM-001"));

        DuplicateScenarioCodeException ex = assertThrows(
                DuplicateScenarioCodeException.class,
                () -> decorator.createScenario(command)
        );

        assertTrue(ex.getMessage().contains("SCN-CUSTOM-001"));
        verify(transactionalDelegate, times(1)).createScenario(command);
    }

    @Test
    @DisplayName("Client chỉ định mã gặp DataIntegrityViolationException ở DB -> Dịch thành DuplicateScenarioCodeException và không retry")
    void testCreateScenario_ClientProvidedCode_DataIntegrityViolation_ThrowsDuplicateCodeWithoutRetry() {
        CreateScenarioCommand command = new CreateScenarioCommand(
                "SCN-CUSTOM-002", "Kịch bản test", "Mô tả", 10L, 2026, 38, 8
        );

        when(transactionalDelegate.createScenario(command))
                .thenThrow(new DataIntegrityViolationException("uk_scenario_code violation"));

        DuplicateScenarioCodeException ex = assertThrows(
                DuplicateScenarioCodeException.class,
                () -> decorator.createScenario(command)
        );

        assertTrue(ex.getMessage().contains("SCN-CUSTOM-002"));
        verify(transactionalDelegate, times(1)).createScenario(command);
    }

    @Test
    @DisplayName("Mã sinh tự động bị trùng ở lần 1 -> Retry lần 2 thành công trong transaction mới")
    void testCreateScenario_AutoGeneratedCode_CollidesOnce_RetriesSuccessfully() {
        CreateScenarioCommand command = new CreateScenarioCommand(
                null, "Kịch bản tự động", "Mô tả", 10L, 2026, 38, 8
        );

        ScenarioResult expectedResult = new ScenarioResult(
                1L, "SCN-2026-RETRY1", "Kịch bản tự động", "Mô tả", 10L, "Phòng Kỹ Thuật",
                "draft", 2026, 38, 8, LocalDateTime.now(), 103L, "rm_user",
                LocalDateTime.now(), null, 0, 5
        );

        when(transactionalDelegate.createScenario(command))
                .thenThrow(new DuplicateScenarioCodeException("SCN-2026-DUPLICATE"))
                .thenReturn(expectedResult);

        ScenarioResult result = decorator.createScenario(command);

        assertNotNull(result);
        assertEquals("SCN-2026-RETRY1", result.code());
        verify(transactionalDelegate, times(2)).createScenario(command);
    }

    @Test
    @DisplayName("Mã sinh tự động vượt quá số lần retry tối đa -> Ném ngoại lệ")
    void testCreateScenario_AutoGeneratedCode_ExceedsMaxRetries_ThrowsException() {
        CreateScenarioCommand command = new CreateScenarioCommand(
                null, "Kịch bản tự động", "Mô tả", 10L, 2026, 38, 8
        );

        when(transactionalDelegate.createScenario(command))
                .thenThrow(new DuplicateScenarioCodeException("SCN-2026-DUP"));

        assertThrows(
                DuplicateScenarioCodeException.class,
                () -> decorator.createScenario(command)
        );

        verify(transactionalDelegate, times(3)).createScenario(command);
    }
}
