app.gmail.credentials-path=${GMAIL_CREDENTIALS_PATH:backend/credentials/credentials.json}
app.gmail.tokens-directory-path=${GMAIL_TOKENS_DIRECTORY_PATH:backend/tokens}
app.gmail.oauth-port=${GMAIL_OAUTH_PORT:8889}
app.email-outbox.poll-delay-ms=5000
