package com.hrm.employeemanagement.domain.notification;

public enum NotificationType {
    TASK_MENTION,
    TASK_COMMENT,
    TASK_ASSIGNED,
    TIMESHEET_REMINDER,
    SCHEDULE_CONFLICT,
    ALLOCATION_CHANGED,
    NOTIFICATION_DIGEST,
    TASK_DUE_REMINDER,
    LEAVE_SUBMITTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCEL_REQUESTED,
    OUTSOURCED_CONTRACT_EXPIRING
}

